### ISSUE TITLE
Saved Game Malfunction 

### ISSUE THREAD

**Issue by jordanrsas** [Unity-Technologies/HuaweiServiceSample#18]
When I try to use the Saved Games functions shows me 7013 error, event after do the Login and silentSignIn. 

I try to do the functionality even in the Demo Project but I have same error.

**Comment by CoffeyMiao** [comment]
Hi @jordanrsas, please confirm that you have opened Account Kit, Drive Kit and Game Service under _AppGallery Connect console> your Project> Project settings> Manage APIs_, If it is already open, please close and then open the switch.

To use the saved game function, you need to obtain the DRIVE_APP_DATA permission scope before logging in, you can refer to the `GrantDriveAccess()` method in the demo.

**Comment by jordanrsas** [comment]
perfect, thank you very much
