### ISSUE TITLE
Unity IAP doesn't work after implementing HuaweiService

### ISSUE THREAD

**Issue by dmitry-vasiliev-dc** [Unity-Technologies/HuaweiServiceSample#20]
Purchases in my game don't work after repacking in UDP Console. 
They worked before implementing HuaweiService.
I am using: 
Unity IAP version - 3.2.3
HuaweiService version - 2.0.1

Should I switch from Unity IAP to UDP IAP?

**Comment by marcuslao** [comment]
Hi, do you have any detailed logs or error messages that you can provide us for reference? Thank you!

**Comment by marcuslao** [comment]
Hi, @dmitry-vasiliev-dc  Does the issue still exist? It is not necessary to switch from Unity IAP to UDP. If the issue still exists, please share the log so that we can check.

**Comment by dmitry-vasiliev-dc** [comment]
Hi, sorry, already switched to UDP IAP and can't check right now.
